export const SITE = {
  name: "32onHerold Holidays",
  tagline: "Discover the world with 32onH Holidays. We create unforgettable travel experiences tailored to your dreams and desires.",
  address: "Somerset West, Cape Town, South Africa",
  email: "travel@pjfmarkgraaff.co.za",
  social: "@32_on_herold",
  officeHours: ["Mon – Fri: 8:00 AM – 4:00 PM", "Saturday: 9:00 AM – 12:00 PM"],
  nav: [
    { label: "Home", href: "/" },
    { label: "Destinations", href: "/destinations" },
    { label: "Packages", href: "/packages" },
    { label: "Contact", href: "/contact" },
  ],
};

export const DESTINATIONS = [
  {
    slug: "istanbul",
    country: "Turkey",
    flag: "🇹🇷",
    name: "Istanbul",
    rating: "4.8",
    description: "A vibrant city bridging Europe and Asia. Istanbul offers a rich tapestry of history, culture, and stunning architecture.",
    bestTime: "Spring to Autumn",
    duration: "4–8",
    image: "https://picsum.photos/seed/istanbul/800/600",
  },
  {
    slug: "mauritius",
    country: "Mauritius",
    flag: "🇲🇺",
    name: "Mauritius",
    rating: "4.9",
    description: "An island nation known for its beaches, lagoons, and reefs. The mountainous interior includes Black River Gorges National Park.",
    bestTime: "May to December",
    duration: "7–14",
    image: "https://picsum.photos/seed/mauritius/800/600",
  },
  {
    slug: "maldives",
    country: "Maldives",
    flag: "🇲🇻",
    name: "Maldives",
    rating: "4.9",
    description: "A tropical nation in the Indian Ocean comprised of 26 ring-shaped atolls, made up of more than 1,000 coral islands.",
    bestTime: "November to April",
    duration: "7–10",
    image: "https://picsum.photos/seed/maldives/800/600",
  },
  {
    slug: "zanzibar",
    country: "Zanzibar",
    flag: "🇹🇿",
    name: "Zanzibar",
    rating: "4.7",
    description: "Discover the spice island of Zanzibar with its rich history and stunning beaches.",
    bestTime: "June to October",
    duration: "7–10",
    image: "https://picsum.photos/seed/zanzibar/800/600",
  },
  {
    slug: "seychelles",
    country: "Seychelles",
    flag: "🇸🇨",
    name: "Seychelles",
    rating: "4.8",
    description: "Explore the breathtaking islands of Seychelles with pristine beaches and marine life.",
    bestTime: "April to May",
    duration: "7–10",
    image: "https://picsum.photos/seed/seychelles/800/600",
  },
  {
    slug: "phuket",
    country: "Thailand",
    flag: "🇹🇭",
    name: "Phuket",
    rating: "4.7",
    description: "Thailand's largest island offers stunning beaches, vibrant nightlife, and rich cultural heritage.",
    bestTime: "November to April",
    duration: "7–14",
    image: "https://picsum.photos/seed/phuket/800/600",
  },
  {
    slug: "belgium",
    country: "Belgium",
    flag: "🇧🇪",
    name: "Belgium",
    rating: "4.6",
    description: "Discover charming medieval towns, world-class museums, and the finest chocolate and beer in Europe.",
    bestTime: "April to September",
    duration: "5–10",
    image: "https://picsum.photos/seed/belgium/800/600",
  },
  {
    slug: "bali",
    country: "Indonesia",
    flag: "🇮🇩",
    name: "Bali",
    rating: "4.8",
    description: "The Island of the Gods offers lush rice terraces, ancient temples, volcanic mountains, and a vibrant arts scene.",
    bestTime: "April to October",
    duration: "7–14",
    image: "https://picsum.photos/seed/bali/800/600",
  },
  {
    slug: "paris",
    country: "France",
    flag: "🇫🇷",
    name: "Paris",
    rating: "4.7",
    description: "The City of Light dazzles with world-class art, iconic landmarks, exquisite cuisine, and unmatched romance.",
    bestTime: "April to June",
    duration: "5–10",
    image: "https://picsum.photos/seed/paris/800/600",
  },
  {
    slug: "cape-town",
    country: "South Africa",
    flag: "🇿🇦",
    name: "Cape Town",
    rating: "4.8",
    description: "A breathtaking city at the tip of Africa offering dramatic mountains, pristine beaches, and world-famous wines.",
    bestTime: "November to March",
    duration: "5–10",
    image: "https://picsum.photos/seed/capetown/800/600",
  },
];

export const PACKAGES = [
  {
    slug: "mauritius-paradise",
    destination: "Mauritius",
    name: "Mauritius Paradise Getaway",
    description: "Experience the pristine beaches, crystal-clear waters, and luxury resorts of Mauritius.",
    image: "https://picsum.photos/seed/mauritius-pkg/800/600",
  },
  {
    slug: "zanzibar-cultural",
    destination: "Zanzibar",
    name: "Zanzibar Cultural Adventure",
    description: "Discover the spice island of Zanzibar with its rich history and stunning beaches.",
    image: "https://picsum.photos/seed/zanzibar-pkg/800/600",
  },
  {
    slug: "seychelles-island-hopping",
    destination: "Seychelles",
    name: "Seychelles Island Hopping",
    description: "Explore the breathtaking islands of Seychelles with pristine beaches and marine life.",
    image: "https://picsum.photos/seed/seychelles-pkg/800/600",
  },
];

export const TESTIMONIALS = [
  {
    name: "Maryna van Staden",
    trip: "Phuket Island Hopper",
    quote: "Thank you 32onHerold for our unforgettable holiday in Phuket, Thailand. It was a seamless dreamlike escape and it's all because you tailored every detail to our taste. We are already planning our next trip through your travel agency.",
  },
  {
    name: "Ansa Greyvenstein",
    trip: "Unforgettable Zanzibar Magic",
    quote: "If you're dreaming of Zanzibar, stop searching and book with 32 on Herold. From start to finish, they orchestrated a flawless and unforgettable holiday. The Accommodation they selected was stunning. Every Rand was well spent. 32 on Herold didn't just organized a trip, they created memories we'll cherish forever.",
  },
  {
    name: "Anna-Mart Peens",
    trip: "Belgium Holiday",
    quote: "Our trip to Belgium planned by 32 on Herold was absolutely wonderful! Every detail was so well thought out, and we felt completely taken care of from start to finish. Thanks to their guidance we discovered hidden gems, enjoyed the most charming towns, and truly experienced the heart of Belgium. We came home with beautiful memories and so much gratitude for the care and passion they put into our journey. Highly recommend them! 🤍",
  },
];

export const HOTEL_CODES = [
  { code: "CAN", name: "Canonnier Beachcomber", stars: 4 },
  { code: "MAU", name: "Mauricia Beachcomber", stars: 4 },
  { code: "VIC", name: "Victoria Beachcomber", stars: 4 },
  { code: "SHA", name: "Shandrani Beachcomber", stars: 4 },
  { code: "TAB", name: "Trou aux Biches Beachcomber", stars: 5 },
  { code: "PAR", name: "Paradis Beachcomber", stars: 5 },
  { code: "DIN", name: "Dinarobin Beachcomber", stars: 5 },
  { code: "RP", name: "Royal Palm Beachcomber", stars: 5 },
];

export const DEPARTURE_CITIES = ["Cape Town", "Johannesburg", "Durban"];

export const STAR_GRADINGS = ["No Preference", "3 Star", "4 Star", "4 Star Superior", "5 Star"];
